Search.appendIndex(
    [
                {
            "fqsen": "\\Pantry\\Basket",
            "name": "Basket",
            "summary": "",
            "url": "classes/Pantry-Basket.html"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Basket\u0020constructor.",
            "url": "classes/Pantry-Basket.html#method___construct"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Returns\u0020the\u0020basket\u0020data\u0020as\u0020json.",
            "url": "classes/Pantry-Basket.html#method___toString"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Returns\u0020the\u0020basket\u0020data\u0020as\u0020an\u0020object.",
            "url": "classes/Pantry-Basket.html#method___invoke"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020the\u0020basket\u0020data\u0020as\u0020an\u0020object.",
            "url": "classes/Pantry-Basket.html#method_get"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003A__debugInfo\u0028\u0029",
            "name": "__debugInfo",
            "summary": "Returns\u0020the\u0020basket\u0020data\u0020as\u0020an\u0020array.",
            "url": "classes/Pantry-Basket.html#method___debugInfo"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020the\u0020basket\u0020with\u0020the\u0020given\u0020data.",
            "url": "classes/Pantry-Basket.html#method_update"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020the\u0020basket.",
            "url": "classes/Pantry-Basket.html#method_delete"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Pantry-Basket.html#property_data"
        },                {
            "fqsen": "\\Pantry\\Basket\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Pantry-Basket.html#property_name"
        },                {
            "fqsen": "\\Pantry\\Client",
            "name": "Client",
            "summary": "",
            "url": "classes/Pantry-Client.html"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Client\u0020constructor.",
            "url": "classes/Pantry-Client.html#method___construct"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Performs\u0020a\u0020request\u0020to\u0020the\u0020getpantry\u0020API",
            "url": "classes/Pantry-Client.html#method_request"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Gets\u0020information\u0020about\u0020the\u0020pantry.",
            "url": "classes/Pantry-Client.html#method_getData"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Returns\u0020the\u0020pantry\u0020data\u0020as\u0020json.",
            "url": "classes/Pantry-Client.html#method___toString"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Returns\u0020the\u0020pantry\u0020data\u0020as\u0020an\u0020object.",
            "url": "classes/Pantry-Client.html#method___invoke"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020the\u0020pantry\u0020data\u0020as\u0020an\u0020object.",
            "url": "classes/Pantry-Client.html#method_get"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A__debugInfo\u0028\u0029",
            "name": "__debugInfo",
            "summary": "Returns\u0020the\u0020pantry\u0020data\u0020as\u0020an\u0020array.",
            "url": "classes/Pantry-Client.html#method___debugInfo"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020the\u0020pantry\u0020with\u0020the\u0020given\u0020data.",
            "url": "classes/Pantry-Client.html#method_update"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003AgetBasket\u0028\u0029",
            "name": "getBasket",
            "summary": "Gets\u0020information\u0020about\u0020a\u0020basket.",
            "url": "classes/Pantry-Client.html#method_getBasket"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003AcreateBasket\u0028\u0029",
            "name": "createBasket",
            "summary": "Creates\u0020a\u0020new\u0020basket.",
            "url": "classes/Pantry-Client.html#method_createBasket"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003APANTRY_URL",
            "name": "PANTRY_URL",
            "summary": "",
            "url": "classes/Pantry-Client.html#constant_PANTRY_URL"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A\u0024pantryID",
            "name": "pantryID",
            "summary": "",
            "url": "classes/Pantry-Client.html#property_pantryID"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A\u0024async",
            "name": "async",
            "summary": "",
            "url": "classes/Pantry-Client.html#property_async"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A\u0024HttpClient",
            "name": "HttpClient",
            "summary": "",
            "url": "classes/Pantry-Client.html#property_HttpClient"
        },                {
            "fqsen": "\\Pantry\\Client\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Pantry-Client.html#property_data"
        },                {
            "fqsen": "\\Pantry\\Exceptions\\BasketNotFoundException",
            "name": "BasketNotFoundException",
            "summary": "",
            "url": "classes/Pantry-Exceptions-BasketNotFoundException.html"
        },                {
            "fqsen": "\\Pantry\\Exceptions\\PantryException",
            "name": "PantryException",
            "summary": "",
            "url": "classes/Pantry-Exceptions-PantryException.html"
        },                {
            "fqsen": "\\Pantry\\Exceptions\\RequestException",
            "name": "RequestException",
            "summary": "",
            "url": "classes/Pantry-Exceptions-RequestException.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Pantry",
            "name": "Pantry",
            "summary": "",
            "url": "namespaces/pantry.html"
        },                {
            "fqsen": "\\Pantry\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/pantry-exceptions.html"
        }            ]
);
